### PR TITLE
fix(axis): include defaultTextProps in Axis labelProps

### LINKED ISSUE #1790: <Axis /> labelProps is documented as Partial, but overwrites values
Setting a fill color like so:

```tsx
<Axis
    labelProps={{
      fill: AXIS_TEXT_COLOR,
    }}
/>
```

overwrites all other label props.

### PR DESCRIPTION
**Pull request by RyKilleen**
#### :bug: Bug Fix

- Enables passing of partial labelProps per the docs

Closes #1790

### CODE REVIEW

File: packages/visx-axis/src/axis/AxisRenderer.tsx [hunk 1]
```diff
@@ -42,6 +42,10 @@ export default function AxisRenderer<Scale extends AxisScale>({
   ticks,
   ticksComponent = Ticks,
 }: AxisRendererProps<Scale>) {
+  const labelPropsDefault = {
+    ...defaultTextProps,
+    ...labelProps
+  }
```
Comment (williaster) [inline packages/visx-axis/src/axis/AxisRenderer.tsx:48]: I think linting will complain about the missing `,`. Could potentially tweak the name here as well (super nit, wouldn't have suggested without the `,` fix)

```suggestion
  const combinedLabelProps = {
    ...defaultTextProps,
    ...labelProps,
  }
```

**Review by williaster — COMMENTED** [review]
Thanks for the fix here/making it consistent with `tickLabelProps`! (that behavior was added relatively recently in https://github.com/airbnb/visx/pull/1662)

Technically this could be thought of as a breaking change as it would change existing behavior if consumers expect to provide all props. However for `tickLabelProps` we just made it a `minor` version bump so we can do that here. I agree this is a better dev x.

File: packages/visx-axis/src/axis/AxisRenderer.tsx [hunk 2]
```diff
@@ -89,13 +93,13 @@ export default function AxisRenderer<Scale extends AxisScale>({
           className={cx('visx-axis-label', labelClassName)}
           {...getLabelTransform({
             labelOffset,
-            labelProps,
+            labelPropsDefault,
```
Comment (williaster) [inline packages/visx-axis/src/axis/AxisRenderer.tsx:96]: Looks like TS is failing because this is a named argument

```suggestion
            labelProps: combinedLabelProps,
```

**Comment by RyKilleen** [comment]
Thanks @williaster! Suggested changes applied.

File: packages/visx-axis/src/axis/AxisRenderer.tsx [hunk 3]
```diff
@@ -89,13 +93,13 @@ export default function AxisRenderer<Scale extends AxisScale>({
...
             labelOffset,
-            labelProps,
+            labelProps: combinedLabelProps,
             orientation,
             range: scale.range(),
             tickLabelFontSize: maxTickLabelFontSize,
             tickLength,
           })}
-          {...labelProps}
+          {...labelPropsDefault}
```
Comment (williaster) [inline packages/visx-axis/src/axis/AxisRenderer.tsx:102]:
```suggestion
          {...combinedLabelProps}
```

**Review by williaster — COMMENTED** [review]
sorry missed one spot that I think needs to include the superset of props. else lgtm! thanks for the followup 🙏

File: packages/visx-axis/src/axis/AxisRenderer.tsx [hunk 4]
```diff
@@ -42,6 +42,10 @@ export default function AxisRenderer<Scale extends AxisScale>({
   ticks,
   ticksComponent = Ticks,
 }: AxisRendererProps<Scale>) {
+  const combinedLabelProps = {
+    ...defaultTextProps,
+    ...labelProps,
+  }
```
[the remark this answers is not in the document]
Comment (RyKilleen) [reply packages/visx-axis/src/axis/AxisRenderer.tsx:48]: No worries, I could have been more thorough in my first pass! Pure hubris to think I could do it through GH UI alone 😄

[the remark this answers is not in the document]
Comment (williaster) [reply packages/visx-axis/src/axis/AxisRenderer.tsx]: haha np 😅  thanks for the multiple cycles

**Review by williaster — APPROVED** [review]
thanks again @RyKilleen ! 🙏
